---
title: "lazyWorkers"
author: "ES"
date: "7/24/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# load packages
```{r}
library(ggplot2)  # plots
library(lme4)     # glmms
library(tidyverse)# piping
library(ggpubr)   # ggdensity plots
library(car)      # qqp
library(sjPlot)   # tab_model summary
library(MuMIn)    # model.sel
library(multcomp) # glht posthoc test
```

# load data
```{r}
nSpec <- read.csv("../Data/filtData/nSpecialists.csv")
nSpecTime <- read.csv("../Data/filtData/nSpecialistsTime.csv")
```

# format nSpec data for glmms
```{r}
# remove specialists on things other than lazy, and rename to nLaz
nLaz <- nSpec[nSpec$specBehav == "lazy",]

# rename nBeesPerNest for clarity that they are lazy
names(nLaz)[names(nLaz) == "nBeesPerNest"] <- "nLazy"

# add in number of bees in the nest as an additional column (based on nestTYPE)
nLaz$totalBees <- NA
nLaz$totalBees[nLaz$nestTYPE == "QF"] <- 6
nLaz$totalBees[nLaz$nestTYPE == "NF"] <- 5
nLaz$totalBees[nLaz$nestTYPE == "QT"] <- 4
nLaz$totalBees[nLaz$nestTYPE == "NT"] <- 3

nLaz
```

# visualize nLaz
```{r}
ggplot(nLaz, aes(nLazy, nestTYPE, color = nestTYPE)) +
  geom_point(position = position_jitter(width=0.2, height=0.2), alpha = 0.6) +
  stat_summary(fun = mean, geom = "point", size = 5) +
  scale_shape_manual(values = c(17, 25)) +
  labs(x = "number of bees with 0-2 observations per nest")
ggsave("../figures/lazyBees.jpg")
```

# format nSpecTime data for glmms
```{r}
# remove specialists on things other than lazy, and rename to nLazTime
nLazTime <- nSpecTime[nSpecTime$specBehav == "lazy",]

# rename nBeesPerNest for clarity that they are lazy
names(nLazTime)[names(nLazTime) == "nBeesPerNest"] <- "nLazy"

nLazTime$totalBees <- NA
nLazTime$totalBees[nLazTime$nestTYPE == "QF"] <- 6
nLazTime$totalBees[nLazTime$nestTYPE == "NF"] <- 5
nLazTime$totalBees[nLazTime$nestTYPE == "QT"] <- 4
nLazTime$totalBees[nLazTime$nestTYPE == "NT"] <- 3

nLazTime
```

# visualize nLazTime
```{r}
ggplot(nLazTime, aes(nLazy, nestTYPE, color = nestTYPE, shape = timepoint)) +
  geom_point(position = position_jitter(width=0.2, height=0.2), alpha = 0.6) +
  stat_summary(fun = mean, geom = "point", size = 5) +
  scale_shape_manual(values = c(17, 25)) +
  labs(x = "number of bees with 0-2 observations per nest")
ggsave("../figures/lazyBeesTime.jpg")
```

# add natal colony to nLaz and nLazTime dfs
```{r}
# cleanMasterData no longer exists -- need to edit this if we want to include natal colony in analyses

# master <- read.csv("../Data/CleanMasterData.csv")
# master
# 
# # make a new column in nLaz for natal colony
# nLaz$natal <- NA
# # for each nest in the nLaz df
# for (i in 1:nrow(nLaz)) {
#   # go through master until you find the matching nestID
#   for (j in 1:nrow(master)) {
#     # if the nest ID matches
#     if (nLaz$nestID[i] == master$nestID[j]) {
#         nLaz$natal[i] <- master$Wnatal[j]
#       }
#     }
# }
# 
# 
# # make a new column in nLazTime for natal colony
# nLazTime$natal <- NA
# # for each bee in the nLazTime df
# for (i in 1:nrow(nLazTime)) {
#   # go through master until you find the matching nestID
#   for (j in 1:nrow(master)) {
#     # if the nest ID matches
#     if (nLazTime$nestID[i] == master$nestID[j]) {
#         nLazTime$natal[i] <- master$Wnatal[j]
#       }
#     }
#   }
```


# glmms on number of lazy workers across nestTYPEs
```{r}
# it's not normal - lnorm probs
ggdensity(nLaz$nLazy)
qqp(nLaz$nLazy, "norm")

# still need to add natal colony as random effect
ps <- glm(nLazy ~ totalBees, 
          data = nLaz, family = poisson(link = "log"))
mymodel <- ps
tab_model(mymodel)

# plot model residuals
plot(fitted(mymodel), residuals(mymodel), xlab = "Fitted Values", ylab = "Residuals")
abline(h = 0, lty = 2)
lines(smooth.spline(fitted(mymodel), residuals(mymodel)))
```

# glmms on number of lazy workers across timepoints
```{r}
# it's not normal - lnorm probs
ggdensity(nLazTime$nLazy)
qqp(nLazTime$nLazy, "norm")

# need to add natal colony as random effect
ps0 <- glm(nLazy ~ 1, 
          data = nLazTime, family = poisson(link = "log"))
ps1 <- glm(nLazy ~ totalBees + timepoint, 
          data = nLazTime, family = poisson(link = "log"))
ps2 <- glm(nLazy ~ totalBees, 
          data = nLazTime, family = poisson(link = "log"))
ps3 <- glm(nLazy ~ timepoint, 
          data = nLazTime, family = poisson(link = "log"))
model.sel(ps0, ps1, ps2, ps3)

mymodel <- ps2
tab_model(mymodel)
# posthoc1 <- glht(mymodel, linfct = mcp(nestTYPE = "Tukey"))
# summary(posthoc1)

# plot model residuals
plot(fitted(mymodel), residuals(mymodel), xlab = "Fitted Values", ylab = "Residuals")
abline(h = 0, lty = 2)
lines(smooth.spline(fitted(mymodel), residuals(mymodel)))
```