---
title: "proportions"
author: "ES"
date: "9/24/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
```

# PROPORTIONS
```{r}
prop <- read.csv("../Data/filtData/prop_bees.csv")

prop <- prop[prop$caste == "W",]
prop$ovS <- rowMeans(prop[,c("ovS1", "ovS2")], na.rm = TRUE)
prop$ovR <- rowMeans(prop[,c("ovR1", "ovR2")], na.rm = TRUE)
prop <- prop[!grepl("unknown", prop$beeID), ]

prop
```

```{r}
# body size

ggplot(prop, aes(x = nectarforaging, y = size)) +
  geom_smooth(method=lm) +
  geom_point(aes(color = shannon, shape = specBehav)) +
  scale_color_gradient(low="dark blue", high="yellow")

ggplot(prop, aes(x = pollenforaging, y = size)) +
  geom_smooth(method=lm) +
  geom_point(aes(color = shannon, shape = specBehav)) +
  scale_color_gradient(low="dark blue", high="yellow")

ggplot(prop, aes(x = feedsbrood, y = size)) +
  geom_smooth(method=lm) +
  geom_point(aes(color = shannon, shape = specBehav)) +
  scale_color_gradient(low="dark blue", high="yellow")

ggplot(prop, aes(x = egglaying, y = size)) +
  geom_smooth(method=lm) +
  geom_point(aes(color = shannon, shape = specBehav)) +
  scale_color_gradient(low="dark blue", high="yellow")
```

```{r}
# ovary stage

ggplot(prop, aes(x = nectarforaging, y = ovS)) +
  geom_smooth(method=lm) +
  geom_point(aes(color = shannon, shape = specBehav)) +
  scale_color_gradient(low="dark blue", high="yellow")

ggplot(prop, aes(x = pollenforaging, y = ovS)) +
  geom_smooth(method=lm) +
  geom_point(aes(color = shannon, shape = specBehav)) +
  scale_color_gradient(low="dark blue", high="yellow")

ggplot(prop, aes(x = feedsbrood, y = ovS)) +
  geom_smooth(method=lm) +
  geom_point(aes(color = shannon, shape = specBehav)) +
  scale_color_gradient(low="dark blue", high="yellow")

ggplot(prop, aes(x = egglaying, y = ovS)) +
  geom_smooth(method=lm) +
  geom_point(aes(color = shannon, shape = specBehav)) +
  scale_color_gradient(low="dark blue", high="yellow")
```

```{r}
# ovary resorption

ggplot(prop, aes(x = nectarforaging, y = ovR)) +
  geom_smooth(method=lm) +
  geom_point(aes(color = shannon, shape = specBehav)) +
  scale_color_gradient(low="dark blue", high="yellow")

ggplot(prop, aes(x = pollenforaging, y = ovR)) +
  geom_smooth(method=lm) +
  geom_point(aes(color = shannon, shape = specBehav)) +
  scale_color_gradient(low="dark blue", high="yellow")

ggplot(prop, aes(x = feedsbrood, y = ovR)) +
  geom_smooth(method=lm) +
  geom_point(aes(color = shannon, shape = specBehav)) +
  scale_color_gradient(low="dark blue", high="yellow")

ggplot(prop, aes(x = egglaying, y = ovR)) +
  geom_smooth(method=lm) +
  geom_point(aes(color = shannon, shape = specBehav)) +
  scale_color_gradient(low="dark blue", high="yellow")
```

# COUNTS
```{r}
count <- read.csv("../Data/filtData/count_data.csv")
count <- count[count$nBehavs > 2,]
count <- count[count$caste == "W",]
count <- count[!grepl("unknown", count$beeID), ]
count$ovS <- rowMeans(count[,c("ovS1", "ovS2")], na.rm = TRUE)
count$ovR <- rowMeans(count[,c("ovR1", "ovR2")], na.rm = TRUE)
```

```{r}
# body size

ggplot(count, aes(x = nectarforaging, y = size)) +
  geom_smooth(method=lm) +
  geom_point(aes(color = shannon, shape = specBehav)) +
  scale_color_gradient(low="dark blue", high="yellow")

ggplot(count, aes(x = pollenforaging, y = size)) +
  geom_smooth(method=lm) +
  geom_point(aes(color = shannon, shape = specBehav)) +
  scale_color_gradient(low="dark blue", high="yellow")

ggplot(count, aes(x = feedsbrood, y = size)) +
  geom_smooth(method=lm) +
  geom_point(aes(color = shannon, shape = specBehav)) +
  scale_color_gradient(low="dark blue", high="yellow")

ggplot(count, aes(x = egglaying, y = size)) +
  geom_smooth(method=lm) +
  geom_point(aes(color = shannon, shape = specBehav)) +
  scale_color_gradient(low="dark blue", high="yellow")
```

```{r}
# ovary stage

ggplot(count, aes(x = nectarforaging, y = ovS)) +
  geom_smooth(method=lm) +
  geom_point(aes(color = shannon, shape = specBehav)) +
  scale_color_gradient(low="dark blue", high="yellow")

ggplot(count, aes(x = pollenforaging, y = ovS)) +
  geom_smooth(method=lm) +
  geom_point(aes(color = shannon, shape = specBehav)) +
  scale_color_gradient(low="dark blue", high="yellow")

ggplot(count, aes(x = feedsbrood, y = ovS)) +
  geom_smooth(method=lm) +
  geom_point(aes(color = shannon, shape = specBehav)) +
  scale_color_gradient(low="dark blue", high="yellow")

ggplot(count, aes(x = egglaying, y = ovS)) +
  geom_smooth(method=lm) +
  geom_point(aes(color = shannon, shape = specBehav)) +
  scale_color_gradient(low="dark blue", high="yellow")
```

```{r}
# ovary resorption

ggplot(count, aes(x = nectarforaging, y = ovR)) +
  geom_smooth(method=lm) +
  geom_point(aes(color = shannon, shape = specBehav)) +
  scale_color_gradient(low="dark blue", high="yellow")

ggplot(count, aes(x = pollenforaging, y = ovR)) +
  geom_smooth(method=lm) +
  geom_point(aes(color = shannon, shape = specBehav)) +
  scale_color_gradient(low="dark blue", high="yellow")

ggplot(count, aes(x = feedsbrood, y = ovR)) +
  geom_smooth(method=lm) +
  geom_point(aes(color = shannon, shape = specBehav)) +
  scale_color_gradient(low="dark blue", high="yellow")

ggplot(count, aes(x = egglaying, y = ovR)) +
  geom_smooth(method=lm) +
  geom_point(aes(color = shannon, shape = specBehav)) +
  scale_color_gradient(low="dark blue", high="yellow")
```