---
title: "shannonBees"
author: "ES"
date: "7/17/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# load packages
```{r, echo = FALSE}
library(ggplot2)  # plots
library(ggpubr)   # ggdensity plots
library(lme4)     # glmms
library(sjPlot)   # model summary
library(multcomp) # tukey tests
library(car)      # qqp
library(MuMIn)    # model.sel
```

# load data
```{r}
# pooled data across timepoints, values are counts
# includes all bees, but only known bees with >=3 observations have shannon values
count_data <- read.csv("../Data/filtData/count_data.csv")

# split across timepoints, includes all bees, but only known bees with >=3 observations have shannon values
count_time <- read.csv("../Data/filtData/count_time.csv")
```

# two part model on pooled shannon across nestTYPES
```{r}
# remove NA shannon values
count_bees <- count_data[!is.na(count_data$shannon),]

# make a new column for over or under 0
count_bees$shan0 <- NA
# if shannon = 0, shan0 = 1
count_bees$shan0[count_bees$shannon == 0] <- 1
# if shannon > 0, shan0 = 0
count_bees$shan0[count_bees$shannon > 0] <- 0


# model 0 vs. >0 shannon values
# need to add natal colony as random effect
ps0 <- glmer(shan0 ~ 1 + (1|nestID) + (1|natal),
              data = count_bees, family = binomial(link = "logit"))
ps1 <- glmer(shan0 ~ nestTYPE + nBehavs + caste + (1|nestID) + (1|natal),
              data = count_bees, family = binomial(link = "logit"))
ps2 <- glmer(shan0 ~ nestTYPE + nBehavs + caste + (1|nestID) + (1|natal),
              data = count_bees, family = binomial(link = "logit"))
ps3 <- glmer(shan0 ~ nestTYPE + caste + (1|nestID) + (1|natal),
              data = count_bees, family = binomial(link = "logit"))
ps4 <- glmer(shan0 ~ nestTYPE + nBehavs + (1|nestID) + (1|natal),
              data = count_bees, family = binomial(link = "logit"))
ps5 <- glmer(shan0 ~ nBehavs + caste + (1|nestID) + (1|natal),
              data = count_bees, family = binomial(link = "logit"))
ps6 <- glmer(shan0 ~ nestTYPE + (1|nestID) + (1|natal),
              data = count_bees, family = binomial(link = "logit"))
ps7 <- glmer(shan0 ~ nBehavs + (1|nestID) + (1|natal),
              data = count_bees, family = binomial(link = "logit"))
ps8 <- glmer(shan0 ~ caste + (1|nestID) + (1|natal),
              data = count_bees, family = binomial(link = "logit"))
model.sel(ps0, ps1, ps2, ps3, ps4, ps5, ps6, ps7, ps8)

mymodel <- ps5
tab_model(mymodel)
# plot model residuals
plot(fitted(mymodel), residuals(mymodel), xlab = "Fitted Values", ylab = "Residuals")
abline(h = 0, lty = 2)
lines(smooth.spline(fitted(mymodel), residuals(mymodel)))

################

# make a new column that contains only shannon for bees with shannon > 0
count_bees$shan1 <- NA
count_bees$shan1[count_bees$shannon > 0] <- count_bees$shannon[count_bees$shannon > 0]
# it's mostly normal
qqp(count_bees$shan1, "norm")

# model 0 vs. >0 shannon values
# need to add natal colony as random effect
ps0 <- glmer(shan1 ~ 1 + (1|nestID)  + (1|natal),
              data = count_bees)
ps1 <- glmer(shan1 ~ nestTYPE + nBehavs + caste + (1|nestID) + (1|natal),
              data = count_bees)
ps2 <- glmer(shan1 ~ nestTYPE + nBehavs + (1|nestID) + (1|natal),
              data = count_bees)
ps3 <- glmer(shan1 ~ nestTYPE + caste + (1|nestID) + (1|natal),
              data = count_bees)
ps4 <- glmer(shan1 ~ nestTYPE + nBehavs + (1|nestID) + (1|natal),
              data = count_bees)
ps5 <- glmer(shan1 ~ nBehavs + caste + (1|nestID) + (1|natal),
              data = count_bees)
ps6 <- glmer(shan1 ~ nestTYPE + (1|nestID) + (1|natal),
              data = count_bees)
ps7 <- glmer(shan1 ~ nBehavs + (1|nestID) + (1|natal),
              data = count_bees)
ps8 <- glmer(shan1 ~ caste + (1|nestID) + (1|natal),
              data = count_bees)
model.sel(ps0, ps1, ps2, ps3, ps4)

mymodel <- ps0
tab_model(mymodel)
# plot model residuals
modelResiduals <- resid(mymodel, type = "pearson") # Extract standardized residuals 
hist(modelResiduals)
```

# glmms on early vs. late shannons
```{r}
# remove NA shannon values
count_beesTime <- count_time[!is.na(count_time$shannon),]

# two part model
# make a new column for over or under 0
count_beesTime$shan0 <- NA
# if shannon = 0, shan0 = 1
count_beesTime$shan0[count_beesTime$shannon == 0] <- 1
# if shannon > 0, shan0 = 0
count_beesTime$shan0[count_beesTime$shannon > 0] <- 0


# model 0 vs. >0 shannon values
# need to add natal colony as random effect
ps0 <- glmer(shan0 ~ 1 + (1|nestID) + (1|natal),
              data = count_beesTime, family = binomial(link = "logit"))
ps1 <- glmer(shan0 ~ timepoint + nestTYPE + nBehavs + caste + (1|nestID) + (1|natal),
              data = count_beesTime, family = binomial(link = "logit"))
ps2 <- glmer(shan0 ~ nestTYPE + nBehavs + caste + (1|nestID) + (1|natal),
              data = count_beesTime, family = binomial(link = "logit"))
ps3 <- glmer(shan0 ~ timepoint + nestTYPE + caste + (1|nestID) + (1|natal),
              data = count_beesTime, family = binomial(link = "logit"))
ps4 <- glmer(shan0 ~ timepoint + nestTYPE + nBehavs + (1|nestID) + (1|natal),
              data = count_beesTime, family = binomial(link = "logit"))
ps5 <- glmer(shan0 ~ timepoint + nBehavs + caste + (1|nestID) + (1|natal),
              data = count_beesTime, family = binomial(link = "logit"))
ps6 <- glmer(shan0 ~ nestTYPE + nBehavs + caste + (1|nestID) + (1|natal),
              data = count_beesTime, family = binomial(link = "logit"))
ps7 <- glmer(shan0 ~ timepoint + nestTYPE + (1|nestID) + (1|natal),
              data = count_beesTime, family = binomial(link = "logit"))
ps8 <- glmer(shan0 ~ timepoint + nBehavs + (1|nestID) + (1|natal),
              data = count_beesTime, family = binomial(link = "logit"))
ps9 <- glmer(shan0 ~ timepoint + caste + (1|nestID) + (1|natal),
              data = count_beesTime, family = binomial(link = "logit"))
ps10 <- glmer(shan0 ~ nestTYPE + caste + (1|nestID) + (1|natal),
              data = count_beesTime, family = binomial(link = "logit"))
ps11 <- glmer(shan0 ~ timepoint + nBehavs + (1|nestID) + (1|natal),
              data = count_beesTime, family = binomial(link = "logit"))
ps12 <- glmer(shan0 ~ nestTYPE + nBehavs + (1|nestID) + (1|natal),
              data = count_beesTime, family = binomial(link = "logit"))
ps13 <- glmer(shan0 ~ nBehavs + caste + (1|nestID) + (1|natal),
              data = count_beesTime, family = binomial(link = "logit"))
ps14 <- glmer(shan0 ~ nestTYPE + (1|nestID) + (1|natal),
              data = count_beesTime, family = binomial(link = "logit"))
ps15 <- glmer(shan0 ~ nBehavs + (1|nestID) + (1|natal),
              data = count_beesTime, family = binomial(link = "logit"))
ps16 <- glmer(shan0 ~ caste + (1|nestID) + (1|natal),
              data = count_beesTime, family = binomial(link = "logit"))
model.sel(ps0, ps1, ps2, ps3, ps4, ps5, ps6, ps7, ps8, ps9, ps10, ps11, ps12, ps13, ps14, ps15, ps16)

mymodel <- ps15
tab_model(mymodel)
# plot model residuals
plot(fitted(mymodel), residuals(mymodel), xlab = "Fitted Values", ylab = "Residuals")
abline(h = 0, lty = 2)
lines(smooth.spline(fitted(mymodel), residuals(mymodel)))

################

# make a new column that contains only shannon for bees with shannon > 0
count_beesTime$shan1 <- NA
count_beesTime$shan1[count_beesTime$shannon > 0] <- count_beesTime$shannon[count_beesTime$shannon > 0]
# it's mostly normal
hist(count_beesTime$shan1)
qqp(count_beesTime$shan1, "norm")

# model 0 vs. >0 shannon values
# need to add natal colony as random effect
ps0 <- glmer(shan1 ~ 1 + (1|nestID) + (1|natal),
              data = count_beesTime)
ps1 <- glmer(shan1 ~ timepoint + nestTYPE + nBehavs + caste + (1|nestID) + (1|natal),
              data = count_beesTime)
ps2 <- glmer(shan1 ~ nestTYPE + nBehavs + caste + (1|nestID) + (1|natal),
              data = count_beesTime)
ps3 <- glmer(shan1 ~ timepoint + nestTYPE + caste + (1|nestID) + (1|natal),
              data = count_beesTime)
ps4 <- glmer(shan1 ~ timepoint + nestTYPE + nBehavs + (1|nestID) + (1|natal),
              data = count_beesTime)
ps5 <- glmer(shan1 ~ timepoint + nBehavs + caste + (1|nestID) + (1|natal),
              data = count_beesTime)
ps6 <- glmer(shan1 ~ nestTYPE + nBehavs + caste + (1|nestID) + (1|natal),
              data = count_beesTime)
ps7 <- glmer(shan1 ~ timepoint + nestTYPE + (1|nestID) + (1|natal),
              data = count_beesTime)
ps8 <- glmer(shan1 ~ timepoint + nBehavs + (1|nestID) + (1|natal),
              data = count_beesTime)
ps9 <- glmer(shan1 ~ timepoint + caste + (1|nestID) + (1|natal),
              data = count_beesTime)
ps10 <- glmer(shan1 ~ nestTYPE + caste + (1|nestID) + (1|natal),
              data = count_beesTime)
ps11 <- glmer(shan1 ~ timepoint + nBehavs + (1|nestID) + (1|natal),
              data = count_beesTime)
ps12 <- glmer(shan1 ~ nestTYPE + nBehavs + (1|nestID) + (1|natal),
              data = count_beesTime)
ps13 <- glmer(shan1 ~ nBehavs + caste + (1|nestID) + (1|natal),
              data = count_beesTime)
ps14 <- glmer(shan1 ~ nestTYPE + (1|nestID) + (1|natal),
              data = count_beesTime)
ps15 <- glmer(shan1 ~ nBehavs + (1|nestID) + (1|natal),
              data = count_beesTime)
ps16 <- glmer(shan1 ~ caste + (1|nestID) + (1|natal),
              data = count_beesTime)
model.sel(ps0, ps1, ps2, ps3, ps4, ps5, ps6, ps7, ps8, ps9, ps10, ps11, ps12, ps13, ps14, ps15, ps16)

mymodel <- ps0
tab_model(mymodel)

# plot model residuals
plot(fitted(mymodel), residuals(mymodel), xlab = "Fitted Values", ylab = "Residuals")
abline(h = 0, lty = 2)
lines(smooth.spline(fitted(mymodel), residuals(mymodel)))
```

# glmms on change in shannon across timepoints
```{r}
# pretty normal
ggdensity(count_beesTime$shanDist)
qqp(count_beesTime$shanDist, "norm")

# need to add natal colony as random effect
cs0 <- glmer(shanDist ~ 1 + (1|nestID) + (1|natal),
              data = count_beesTime)
cs1 <- glmer(shanDist ~ nestTYPE + caste + (1|nestID) + (1|natal),
              data = count_beesTime)
cs2 <- glmer(shanDist ~ nestTYPE + (1|nestID) + (1|natal),
              data = count_beesTime)
cs3 <- glmer(shanDist ~ caste + (1|nestID) + (1|natal),
              data = count_beesTime)
model.sel(cs0, cs1, cs2, cs3)

mymodel <- cs2
tab_model(mymodel)
posthoc1 <- glht(mymodel, linfct = mcp(nestTYPE = "Tukey"))
summary(posthoc1)

# plot model residuals
plot(fitted(mymodel), residuals(mymodel), xlab = "Fitted Values", ylab = "Residuals")
abline(h = 0, lty = 2)
lines(smooth.spline(fitted(mymodel), residuals(mymodel)))
```

# tally specialists switching across timepoints
```{r}
# condense df so each bee is one row with early/late specializations as separate columns
specSwitch <- pivot_wider(data = count_time, 
                          id_cols = c("nestID", "nestTYPE", "beeID", "caste", "natal"),
                          names_from = timepoint,
                          values_from = specBehav)
# remove unknown bees, which we don't want to include in this analysis
specSwitch <- specSwitch[!grepl("unknown", specSwitch$beeID),]
specSwitch

# tally switches
## rename NA to "lazy"
specSwitch[is.na(specSwitch$early), "early"] <- "lazy"
specSwitch[is.na(specSwitch$late), "late"] <- "lazy"
## name the behavioral specializations
behavs <- unique(specSwitch$early)
behavs
## make a df with each row and column as each behavior
tallySwitches <- matrix(0, nrow = length(behavs), ncol = length(behavs))
tallySwitches <- as.data.frame(tallySwitches)
rownames(tallySwitches) <- behavs
colnames(tallySwitches) <- behavs
## tally the switches
for(i in 1:nrow(specSwitch)) {
  if(specSwitch$early[i] == "feedsbrood") {
    if(specSwitch$late[i] == "feedsbrood") {
      tallySwitches["feedsbrood", "feedsbrood"] <- tallySwitches["feedsbrood", "feedsbrood"] + 1
    }
    if(specSwitch$late[i] == "nectarforaging") {
      tallySwitches["feedsbrood", "nectarforaging"] <- tallySwitches["feedsbrood", "nectarforaging"] + 1
    }
    if(specSwitch$late[i] == "pollenforaging") {
      tallySwitches["feedsbrood", "pollenforaging"] <- tallySwitches["feedsbrood", "pollenforaging"] + 1
    }
    if(specSwitch$late[i] == "generalist") {
      tallySwitches["feedsbrood", "generalist"] <- tallySwitches["feedsbrood", "generalist"] + 1
    }
    if(specSwitch$late[i] == "lazy") {
      tallySwitches["feedsbrood", "lazy"] <- tallySwitches["feedsbrood", "lazy"] + 1
    }
  }
  if(specSwitch$early[i] == "nectarforaging") {
    if(specSwitch$late[i] == "feedsbrood") {
      tallySwitches["nectarforaging", "feedsbrood"] <- tallySwitches["nectarforaging", "feedsbrood"] + 1
    }
    if(specSwitch$late[i] == "nectarforaging") {
      tallySwitches["nectarforaging", "nectarforaging"] <- tallySwitches["nectarforaging", "nectarforaging"] + 1
    }
    if(specSwitch$late[i] == "pollenforaging") {
      tallySwitches["nectarforaging", "pollenforaging"] <- tallySwitches["nectarforaging", "pollenforaging"] + 1
    }
    if(specSwitch$late[i] == "generalist") {
      tallySwitches["nectarforaging", "generalist"] <- tallySwitches["nectarforaging", "generalist"] + 1
    }
    if(specSwitch$late[i] == "lazy") {
      tallySwitches["nectarforaging", "lazy"] <- tallySwitches["nectarforaging", "lazy"] + 1
    }
  }
  if(specSwitch$early[i] == "pollenforaging") {
    if(specSwitch$late[i] == "feedsbrood") {
      tallySwitches["pollenforaging", "feedsbrood"] <- tallySwitches["pollenforaging", "feedsbrood"] + 1
    }
    if(specSwitch$late[i] == "nectarforaging") {
      tallySwitches["pollenforaging", "nectarforaging"] <- tallySwitches["pollenforaging", "nectarforaging"] + 1
    }
    if(specSwitch$late[i] == "pollenforaging") {
      tallySwitches["pollenforaging", "pollenforaging"] <- tallySwitches["pollenforaging", "pollenforaging"] + 1
    }
    if(specSwitch$late[i] == "generalist") {
      tallySwitches["pollenforaging", "generalist"] <- tallySwitches["pollenforaging", "generalist"] + 1
    }
    if(specSwitch$late[i] == "lazy") {
      tallySwitches["pollenforaging", "lazy"] <- tallySwitches["pollenforaging", "lazy"] + 1
    }
  }
  if(specSwitch$early[i] == "generalist") {
    if(specSwitch$late[i] == "feedsbrood") {
      tallySwitches["generalist", "feedsbrood"] <- tallySwitches["generalist", "feedsbrood"] + 1
    }
    if(specSwitch$late[i] == "nectarforaging") {
      tallySwitches["generalist", "nectarforaging"] <- tallySwitches["generalist", "nectarforaging"] + 1
    }
    if(specSwitch$late[i] == "pollenforaging") {
      tallySwitches["generalist", "pollenforaging"] <- tallySwitches["generalist", "pollenforaging"] + 1
    }
    if(specSwitch$late[i] == "generalist") {
      tallySwitches["generalist", "generalist"] <- tallySwitches["generalist", "generalist"] + 1
    }
    if(specSwitch$late[i] == "lazy") {
      tallySwitches["generalist", "lazy"] <- tallySwitches["generalist", "lazy"] + 1
    }
  }
  if(specSwitch$early[i] == "lazy") {
    if(specSwitch$late[i] == "feedsbrood") {
      tallySwitches["lazy", "feedsbrood"] <- tallySwitches["lazy", "feedsbrood"] + 1
    }
    if(specSwitch$late[i] == "nectarforaging") {
      tallySwitches["lazy", "nectarforaging"] <- tallySwitches["lazy", "nectarforaging"] + 1
    }
    if(specSwitch$late[i] == "pollenforaging") {
      tallySwitches["lazy", "pollenforaging"] <- tallySwitches["lazy", "pollenforaging"] + 1
    }
    if(specSwitch$late[i] == "generalist") {
      tallySwitches["lazy", "generalist"] <- tallySwitches["lazy", "generalist"] + 1
    }
    if(specSwitch$late[i] == "lazy") {
      tallySwitches["lazy", "lazy"] <- tallySwitches["lazy", "lazy"] + 1
    }
  }
}
tallySwitches
```