---
title: "beeSpecialization"
author: "ES"
date: "7/16/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# load packages
```{r}
library(tidyverse)
library(dplyr)
library(ggplot2)
library(cluster) # clustering algorithms
library(factoextra)
library(vegan) 
library(lme4)
library(plotly)
```

# load data
```{r}
bee_data <- read.csv("../Data/beeProp_data.csv")
bee_data
```

# NMDS on pooled beeProp data -- overall individual specialization
```{r}
# Convert dataframes into matrices - two sets: one with combined foraging and one with separated foraging 
# Need to add a unique number to each worker in case there are repeats 

# rename initial count data frame
nmds_data <- beeProp_data
# make NA values 0
nmds_data[is.na(nmds_data)] <- 0

numBees <- nrow(nmds_data)
# remove bees lacking any behaviors
nmds_data <-nmds_data[rowSums(nmds_data[(8:(ncol(nmds_data) - 1))]) > 0, ]
numDatapoints <- nrow(nmds_data)
print(paste( (numBees - numDatapoints), "bees were removed from the nmds data because they had 0 recorded behaviors", sep = " "))

# # add dummy variable to include lazy workers
# nmds_data$nothing <- 0.01

# remove bees with NA beeID
nmds_data <- nmds_data[!is.na(nmds_data$beeID),]
# remane beeID to combine nestID and beeID to account for duplicates
nmds_data$beeID <- paste0(nmds_data$nestID, nmds_data$beeID)
nmds_data

# make matrix of only behavior counts for all timepoints
nmds_all <- as.matrix(nmds_data[,c("feedsbrood", "nectarforaging", "pollenforaging", "egglaying")])

nmds_all

# Run NMDS with euclidean distance
nmds_all <- metaMDS(nmds_all)
plot(nmds_all)

# Get coordinates to graph it 
# Gets NMDS info for each individual
data.scores <- as.data.frame(scores(nmds_all))
data.scores$caste <- nmds_data$caste
data.scores$nestTYPE <-nmds_data$nestTYPE
data.scores$timepoint <-nmds_data$timepoint
data.scores$beeID <-nmds_data$beeID
data.scores$nestID <- nmds_data$nestID
data.scores$nBees <- nmds_data$nBees
data.scores$nWork <- nmds_data$nWork
data.scores$queen <- nmds_data$queen
data.scores

# Gets NMDS info for each behavior
behav.scores<-as.data.frame(scores(nmds_all, "species"))
behav.scores$behav<-rownames(behav.scores)
behav.scores

# Plot it using ggplot
ggplot() + 
  geom_text(data=behav.scores, aes(x=NMDS1, y=NMDS2, label=behav)) +
  geom_point(data=data.scores, aes(x=NMDS1, y=NMDS2, shape=caste, color = nestTYPE), size = 2, position = position_jitter(width=0.08, height=0.08)) + 
  scale_shape_manual(values = c(21, 16)) +
  geom_line(data=data.scores, aes(x=NMDS1, NMDS2, fill = beeID), size = 0.15, position = position_jitter(width = 0, height = 0),
           arrow = arrow(length=unit(0.25,"cm"), type = "open")) +
  coord_cartesian(xlim=c(-1.5, 1.5), ylim=c(-1.5, 2))

# plot it split out by nestID
p <- ggplot() + 
  geom_text(data=behav.scores, aes(x=NMDS1, y=NMDS2, label=behav), size = 2) +
  geom_point(data=data.scores, aes(x=NMDS1, y=NMDS2, shape=caste), position = position_jitter(width=0.05, height=0.05)) + 
  scale_color_manual(values = c("red", "blue")) +
  # geom_line(data=data.scores, aes(x=NMDS1, NMDS2, fill = beeID), size = 0.15,
  #          arrow = arrow(length=unit(0.15,"cm"), type = "open")) +
  coord_cartesian(xlim=c(-2, 2), ylim=c(-2, 2))
plots = data.scores %>%
    do(plots = p %+% . + facet_wrap(~nestID))
plots$plots

# plot split out by nestTYPE
p <- ggplot() + 
  geom_text(data=behav.scores, aes(x=NMDS1, y=NMDS2, label=behav), size = 3) +
  geom_point(data=data.scores, aes(x=NMDS1, y=NMDS2, shape=caste), size = 2, position = position_jitter(width=0.05, height=0.05)) + 
  scale_color_manual(values = c("red", "blue")) +
  # geom_line(data=data.scores, aes(x=NMDS1, NMDS2, fill = beeID), size = 0.15,
  #          arrow = arrow(length=unit(0.15,"cm"), type = "open")) +
  coord_cartesian(xlim=c(-2, 2), ylim=c(-2, 2))
plots = data.scores %>%
    do(plots = p %+% . + facet_wrap(~nestTYPE))
plots$plots
```
```{r}
queen.scores <- data.scores[data.scores$caste == "queen", ]
worker.scores <- data.scores[data.scores$caste == "worker", ]

ggplot(data.scores, aes(NMDS1, fill = nestTYPE)) + geom_density(alpha = 0.3)
ggplot(data.scores, aes(NMDS2, fill = nestTYPE)) + geom_density(alpha = 0.3)

ggplot(queen.scores, aes(NMDS1, fill = nestTYPE)) + geom_density(alpha = 0.3)
ggplot(queen.scores, aes(NMDS2, fill = nestTYPE)) + geom_density(alpha = 0.3)

ggplot(worker.scores, aes(NMDS1, fill = nestTYPE)) + geom_density(alpha = 0.3)
ggplot(worker.scores, aes(NMDS2, fill = nestTYPE)) + geom_density(alpha = 0.3)
```

# glmm on NMDS coordinates in response to nestTYPE, number of bees, and caste
```{r}

# rename for analyses
nmdsData <- data.scores

library(car)
library(MASS)
library(sjPlot)
library(lme4)

nmdsData

############ CAN'T FIGURE OUT CORRECT DISTRIBUTION. ANALYSES ARE INVALID UNTIL THIS IS RESOLVED ############
# normal distribution
qqp(nmdsData$NMDS1, "norm")

# lnorm means lognormal
qqp(nmdsData$NMDS1, "lnorm")

# gamma must be positive numbers
# gamma <- fitdistr(nmdsData$NMDS1, "gamma")
# qqp(nmdsData$NMDS1, "gamma", shape = gamma$estimate[[1]], rate = gamma$estimate[[2]])

# run model on NMDS1: egg laying VS foraging (brood feeding in between)
nmds1 <- glmer(NMDS1 ~ nBees + queen + (1|nestID),
              data = nmdsData)
# p values
tab_model(nmds1)

# run model on NMDS2: brood feeding VS egg laying + foraging
nmds2 <- glmer(NMDS2 ~ nBees + queen + (1|nestID),
              data = nmdsData)
# p values
tab_model(nmds2)
```

# glmm on H across time, nestTYPE, and caste
```{r}
# add a small value to data so that values > 0
alldol$H1 <- alldol$H + 0.01

library(car)
library(MASS)

######################### CAN'T FIGURE OUT DISTRIBUTION. ANALYSES ARE INVALID UNTIL THIS IS RESOLVED ########################

# normal distribution
qqp(alldol$H1, "norm")

# lnorm means lognormal
qqp(alldol$H1, "lnorm")

# gamma must be positive numbers
gamma <- fitdistr(alldol$H1, "gamma")
qqp(alldol$H1, "gamma", shape = gamma$estimate[[1]], rate = gamma$estimate[[2]])

# run model
library(lme4)
dol1 <- glmer(H ~ nestTYPE + caste + timepoint + (1|beeID),
              data = alldol)

# p values
library(sjPlot)
tab_model(dol1)
```
