---
title: "proportionsDFs"
author: "ES"
date: "7/10/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# load packages
```{r}
library(tidyverse)
library(dplyr)
library(plyr)
library(ggplot2)
library(cluster) # clustering algorithms
library(factoextra)
library(vegan) 
library(lme4)
library(plotly)
```

# load data
```{r}
# beeCounts
beeCounts_data <- read.csv("../Data/tempData/beeCounts_filt.csv")
# select only relevant columns
beeCounts_data <- beeCounts_data %>% 
  dplyr::select(nestID, nestTYPE, beeID, caste, nBees, nWork, queen, 
                feedsbrood, nectarforaging, pollenforaging, egglaying, nBehavs)
beeCounts_data$queen <- as.factor(beeCounts_data$queen)
beeCounts_data

beeEarlyCounts_data <- read.csv("../Data/tempData/beeEarlyCounts_filt.csv")
beeEarlyCounts_data <- beeEarlyCounts_data %>% 
  dplyr::select(nestID, nestTYPE, beeID, caste, nBees, nWork, queen, timepoint, 
                feedsbrood, nectarforaging, pollenforaging, nBehavs) # don't include egg laying in early vs. late
beeEarlyCounts_data$queen <- as.factor(beeEarlyCounts_data$queen)
beeEarlyCounts_data

beeLateCounts_data <- read.csv("../Data/tempData/beeLateCounts_filt.csv")
beeLateCounts_data <- beeLateCounts_data %>% 
  dplyr::select(nestID, nestTYPE, beeID, caste, nBees, nWork, queen, timepoint, 
                feedsbrood, nectarforaging, pollenforaging, nBehavs) # don't include egg laying in early vs. late
beeLateCounts_data$queen <- as.factor(beeLateCounts_data$queen)
beeLateCounts_data

# nestCounts
nestCounts_data <- read.csv("../Data/tempData/nestCounts_filt.csv")
nestCounts_data <- nestCounts_data %>% 
  dplyr::select(nestID, nestTYPE, beeID, caste, nBees, nWork, queen, 
                feedsbrood, pollenforaging, nectarforaging, allforaging, egglaying, nBehavs)
nestCounts_data$queen <- as.factor(nestCounts_data$queen)
nestCounts_data
```

# 1. individual specialization
of the behaviors carried out by each individual, proportion of observations of each task
```{r}
# convert counts to proportions out of total behaviors per individual
beeProp_data <- beeCounts_data
beeProp_data$feedsbrood <- beeProp_data$feedsbrood / beeProp_data$nBehavs
beeProp_data$nectarforaging <- beeProp_data$nectarforaging / beeProp_data$nBehavs
beeProp_data$pollenforaging <- beeProp_data$pollenforaging / beeProp_data$nBehavs
beeProp_data$egglaying <- beeProp_data$egglaying / beeProp_data$nBehavs
beeProp_data
write.csv(beeProp_data, "../Data/beeProp_data.csv")

# EARLY and LATE comparisons
beeEarlyProp_data <- beeEarlyCounts_data
beeEarlyProp_data$feedsbrood <- beeEarlyProp_data$feedsbrood / beeEarlyProp_data$nBehavs
beeEarlyProp_data$nectarforaging <- beeEarlyProp_data$nectarforaging / beeEarlyProp_data$nBehavs
beeEarlyProp_data$pollenforaging <- beeEarlyProp_data$pollenforaging / beeEarlyProp_data$nBehavs
beeEarlyProp_data
write.csv(beeEarlyProp_data, "../Data/beeEarlyProp_data.csv")

beeLateProp_data <- beeLateCounts_data
beeLateProp_data$feedsbrood <- beeLateProp_data$feedsbrood / beeLateProp_data$nBehavs
beeLateProp_data$nectarforaging <- beeLateProp_data$nectarforaging / beeLateProp_data$nBehavs
beeLateProp_data$pollenforaging <- beeLateProp_data$pollenforaging / beeLateProp_data$nBehavs
beeLateProp_data
write.csv(beeLateProp_data, "../Data/beeLateProp_data.csv")
```

# 2. task specialization
of all the observations that occur in a given nest, what proportion of individuals carry out each task
```{r}
# first add row with column sums, total number of observations per behavior
# also do this split out by nestID? proportion of bees who carried out each behavior? proportion of bee-observations
# if 10 foraging obs in a nest: [2 by bee A, 1 by bee B, and 7 by bee C]:  A$for = .2, B$for = .1, C$for = .8 

# sum columns for each behavior within each nest
nestCounts_sums <- ddply(nestCounts_data, 
                c("nestID"), 
                summarise,
                feedsbrood = sum(feedsbrood),
                egglaying = sum(egglaying),
                pollenforaging = sum(pollenforaging),
                nectarforaging = sum(nectarforaging),
                allforaging = sum(allforaging),
                nBehavs = sum(nBehavs))
nestCounts_sums

# make df for proportions to be overwritten in loop:
nestProp_data <- nestCounts_data

# for each bee, convert the count of behaviors to the proportion of observations of that behavior for that nest
for (i in 1:nrow(nestCounts_data)) {         # for each bee
  for (j in 1:nrow(nestCounts_sums)) {       # go through the nestCounts_sums df
    if (nestCounts_data$nestID[i] == nestCounts_sums$nestID[j]) {   # until you find the matching nestID
                                             # then divide the counts of each behavior by the total counts of that behavior in the nest
      nestProp_data$feedsbrood[i] <- nestCounts_data$feedsbrood[i] / nestCounts_sums$feedsbrood[j]
      nestProp_data$egglaying[i] <- nestCounts_data$egglaying[i] / nestCounts_sums$egglaying[j]
      nestProp_data$nectarforaging[i] <- nestCounts_data$nectarforaging[i] / nestCounts_sums$nectarforaging[j]
      nestProp_data$pollenforaging[i] <- nestCounts_data$pollenforaging[i] / nestCounts_sums$pollenforaging[j]
      nestProp_data$allforaging[i] <- nestCounts_data$allforaging[i] / nestCounts_sums$allforaging[j]
      nestProp_data$nBehavs[i] <- nestCounts_data$nBehavs[i] / nestCounts_sums$nBehavs[j]
    }
  }
}
nestProp_data
write.csv(nestProp_data, "../Data/nestProp_data.csv")
```

# 3. dol
normalized mutual entropy matrix
```{r}
# first add row with column sums, total number of observations per nest

# sum nBehavs for each behavior within each nest
nestCounts_behav <- ddply(nestCounts_data, 
                c("nestID"), 
                summarise,
                nBehavs = sum(nBehavs))
nestCounts_behav

# make df for proportions to be overwritten in loop:
dol_data <- nestCounts_data

# for each bee, convert the count of behaviors to the proportion of observations of that behavior for that nest
for (i in 1:nrow(dol_data)) {                 # for each bee
  for (j in 1:nrow(nestCounts_behav)) {       # go through the nestCounts_behav df
    if (dol_data$nestID[i] == nestCounts_behav$nestID[j]) {   # until you find the matching nestID
                                              # then divide the counts of each behavior by the total counts of all behaviors in the nest
      dol_data$feedsbrood[i] <- dol_data$feedsbrood[i] / nestCounts_behav$nBehavs[j]
      dol_data$egglaying[i] <- dol_data$egglaying[i] / nestCounts_behav$nBehavs[j]
      dol_data$nectarforaging[i] <- dol_data$nectarforaging[i] / nestCounts_behav$nBehavs[j]
      dol_data$pollenforaging[i] <- dol_data$pollenforaging[i] / nestCounts_behav$nBehavs[j]
      dol_data$allforaging[i] <- dol_data$allforaging[i] / nestCounts_behav$nBehavs[j]
      dol_data$pBehavs[i] <- dol_data$nBehavs[i] / nestCounts_behav$nBehavs[j]
    }
  }
}
dol_data
write.csv(dol_data, "../Data/dol_data.csv")
```