---
title: "lazyWorkers"
author: "ES"
date: "7/24/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# load packages
```{r}
library(ggplot2)   # plots
library(tidyverse) # piping
library(dplyr)     # summarise
```

# load data
```{r}
# load bees with 0 observations
noObsBees <- read.csv("../Data/noObsBees.csv")
noObsBees <- noObsBees[, c("nestID", "beeID")]
noObsBees$uqID <- paste0(noObsBees$nestID, noObsBees$beeID)

# load bees with 1-2 observations
lowCountsBees <- read.csv("../Data/tempData/lowCountsBees.csv")
lowCountsBees <- lowCountsBees[, c("nestID", "beeID")]
lowCountsBees$uqID <- paste0(lowCountsBees$nestID, lowCountsBees$beeID)


# merge together for single df with all bees not included in nmds/dol analyses
lazyBees <- rbind(noObsBees, lowCountsBees)
lazyBees <- lazyBees[!lazyBees$beeID == "unknown",]

# load obs_data to get a list of all the nestIDs
allBees <- read.csv("../Data/allBees.csv")
allBees <- allBees[, c("nestID", "beeID")]
allBees$uqID <- paste0(allBees$nestID, allBees$beeID)
allBees <- allBees[!allBees$beeID == "unknown",]

# to split out by timepoint
obsBeesTime <- read.csv("../Data/countsanalysis.csv")
obsBeesTime <- obsBeesTime[, c("nestID", "beeID", "nBehavs", "timepoint")]
obsBeesTime <- obsBeesTime[!obsBeesTime$beeID == "unknown",]
obsBeesTime$uqID <- paste0(obsBeesTime$nestID, obsBeesTime$beeID)
obsBeesTime$uqID
```

# format and visualize data for number of lazy bees
```{r}
# include all nestIDs so that nests with 0 lazy workers are also included
allNests <- unique(allBees$nestID)
allNests

# add all nests to all dfs
nestsToAdd <- matrix(nrow = length(allNests), ncol = 3)
nestsToAdd <- as.data.frame(nestsToAdd)
colnames(nestsToAdd) <- colnames(noObsBees)
nestsToAdd$nestID <- allNests

noObsBees <- rbind(nestsToAdd, noObsBees)
lowCountsBees <- rbind(nestsToAdd, lowCountsBees)
lazyBees <- rbind(nestsToAdd, lazyBees)

# add nestTYPE column for all dfs
noObsBees$nestTYPE <- substr(noObsBees$nestID, start = 1, stop = 2)
lowCountsBees$nestTYPE <- substr(lowCountsBees$nestID, start = 1, stop = 2)
lazyBees$nestTYPE <- substr(lazyBees$nestID, start = 1, stop = 2)

# order the nestTYPEs so they appear in order of number of bees on graph
noObsBees$nestTYPE <- ordered(noObsBees$nestTYPE, levels = c("NT", "QT", "NF", "QF"))
lowCountsBees$nestTYPE <- ordered(lowCountsBees$nestTYPE, levels = c("NT", "QT", "NF", "QF"))
lazyBees$nestTYPE <- ordered(lazyBees$nestTYPE, levels = c("NT", "QT", "NF", "QF"))

########################### visualize

# zero observations
noObsPerNest <- noObsBees %>% dplyr::group_by(nestID, nestTYPE) %>% dplyr::summarise(nBees = dplyr::n() - 1) # subtract 1 b/c all nests have been added with 0 value

ggplot(noObsPerNest, aes(nBees, nestTYPE, color = nestTYPE)) +
  geom_point(position = position_jitter(width=0.2, height=0.2), alpha = 0.4) +
  stat_summary(fun = mean, geom = "point", size = 5) +
  labs(x = "number of bees with 0 observations per nest")

# 1-2 observations
lowCountsPerNest <- lowCountsBees %>% dplyr::group_by(nestID, nestTYPE) %>% dplyr::summarise(nBees = dplyr::n() - 1) # subtract 1 b/c all nests have been added with 0 value

ggplot(lowCountsPerNest, aes(nBees, nestTYPE, color = nestTYPE)) +
  geom_point(position = position_jitter(width=0.2, height=0.2), alpha = 0.4) +
  stat_summary(fun = mean, geom = "point", size = 5) +
  labs(x = "number of bees with 1-2 observations per nest")

# 0-2 observations
lazyPerNest <- lazyBees %>% dplyr::group_by(nestID, nestTYPE) %>% dplyr::summarise(nBees = dplyr::n() - 1) # subtract 1 b/c all nests have been added with 0 value

ggplot(lazyPerNest, aes(nBees, nestTYPE, color = nestTYPE)) +
  geom_point(position = position_jitter(width=0.2, height=0.2), alpha = 0.4) +
  stat_summary(fun = mean, geom = "point", size = 5) +
  labs(x = "number of bees with 0-2 observations per nest")
ggsave("../figures/lazyBees.jpg")
```

# format and visualize proportion of lazy bee data
```{r}
# 0-2 observations per bee

# add column for the proportion of lazy bees per nest
lazyPerNest$propBees[lazyPerNest$nestTYPE == "NT"] <- lazyPerNest$nBees[lazyPerNest$nestTYPE == "NT"] / 3
lazyPerNest$propBees[lazyPerNest$nestTYPE == "QT"] <- lazyPerNest$nBees[lazyPerNest$nestTYPE == "QT"] / 4
lazyPerNest$propBees[lazyPerNest$nestTYPE == "NF"] <- lazyPerNest$nBees[lazyPerNest$nestTYPE == "NF"] / 5
lazyPerNest$propBees[lazyPerNest$nestTYPE == "QF"] <- lazyPerNest$nBees[lazyPerNest$nestTYPE == "QF"] / 6

# plot it
ggplot(lazyPerNest, aes(propBees, nestTYPE, color = nestTYPE)) +
  geom_point(position = position_jitter(width=0.1, height=0.2), alpha = 0.4) +
  stat_summary(fun = mean, geom = "point", size = 5) +
  labs(x = "proportion of bees with 0-2 observations per nest")
ggsave("../figures/proportionLazyBees.jpg")
```

# look at lazy bees based on timepoint
```{r}
# obsBeesTime are bees with >0 observations overall
# lazyBees are bees with 0 observations ever
# allBees are all of the bees including 0 and >0 observations

# subset bees with high counts at a given timepoint
HIobsBeesTIME <- obsBeesTime[obsBeesTime$nBehavs >= 3, ]
HIobsBeesEARLY <- HIobsBeesTIME[HIobsBeesTIME$timepoint == "early",]
HIobsBeesLATE <- HIobsBeesTIME[HIobsBeesTIME$timepoint == "late",]

# duplicate allBees to include early and late timepoint for each bee
allBeesEARLY <- allBees
allBeesEARLY$timepoint <- "early"
allBeesLATE <- allBees
allBeesLATE$timepoint <- "late"
allBeesTIME <- rbind(allBeesEARLY, allBeesLATE)

# subset allBeesTIME so include only bees that do not have HIobs (i.e., lazy bees with <3 obs at a given timepoint)
lazyBeesEARLY <- subset(allBeesEARLY, !(uqID %in% HIobsBeesEARLY$uqID))
lazyBeesLATE <- subset(allBeesLATE, !(uqID %in% HIobsBeesLATE$uqID))
lazyBeesTIME <- rbind(lazyBeesEARLY, lazyBeesLATE)

# include all nestIDs so that nests with 0 lazy workers are also included
# for both early
allNestsEARLY <- matrix(ncol = 2, nrow = length(unique(allBees$nestID)))
colnames(allNestsEARLY) <- c("nestID", "timepoint")
allNestsEARLY <- as.data.frame(allNestsEARLY)
allNestsEARLY$nestID <- unique(allBees$nestID)
allNestsEARLY$timepoint <- "early"
allNestsEARLY
# and late
allNestsLATE <- matrix(ncol = 2, nrow = length(unique(allBees$nestID)))
colnames(allNestsLATE) <- c("nestID", "timepoint")
allNestsLATE <- as.data.frame(allNestsLATE)
allNestsLATE$nestID <- unique(allBees$nestID)
allNestsLATE$timepoint <- "late"
# then merge early and late together
allNestsTIME <- rbind(allNestsEARLY, allNestsLATE)
allNestsTIME

# merge allNestsTIME and lazyBeesTIME to get df with all lazy bees + one row per nest per timepoint to make sure all nest-timepoints are included 
allNestsTIME$beeID <- NA
allNestsTIME$uqID <- NA
NESTlazyBeesTIME <- rbind(allNestsTIME, lazyBeesTIME)

# add nestTYPE column for all dfs
NESTlazyBeesTIME$nestTYPE <- substr(NESTlazyBeesTIME$nestID, start = 1, stop = 2)

# order the nestTYPEs so they appear in order of number of bees on graph
NESTlazyBeesTIME$nestTYPE <- ordered(NESTlazyBeesTIME$nestTYPE, levels = c("NT", "QT", "NF", "QF"))

########################### visualize

# 0-2 observations
lazyPerNestTIME <- NESTlazyBeesTIME %>% dplyr::group_by(nestID, nestTYPE, timepoint) %>% dplyr::summarise(nBees = dplyr::n() - 1) # subtract 1 b/c all nests have been added with 0 value

ggplot(lazyPerNestTIME, aes(nBees, nestTYPE, color = nestTYPE, shape = timepoint)) +
  geom_point(position = position_jitter(width=0.2, height=0.2), alpha = 0.6) +
  stat_summary(fun = mean, geom = "point", size = 5) +
  scale_shape_manual(values = c(17, 25)) +
  labs(x = "number of bees with 0-2 observations per nest")
ggsave("../figures/lazyBeesTIME.jpg")
```

# add natal colony to lazyPerNest and lazyPerNestTIME dfs
```{r}
master <- read.csv("../Data/CleanMasterData.csv")
master

# make a new column in lazyPerNest for natal colony
lazyPerNest$natal <- NA
# for each bee in the lazyPerNest df
for (i in 1:nrow(lazyPerNest)) {
  # go through master until you find the matching nestID
  for (j in 1:nrow(master)) {
    # if the nest ID matches
    if (lazyPerNest$nestID[i] == master$nestID[j]) {
        lazyPerNest$natal[i] <- master$Wnatal[j]
      }
    }
}


# make a new column in lazyPerNestTIME for natal colony
lazyPerNestTIME$natal <- NA
# for each bee in the lazyPerNestTIME df
for (i in 1:nrow(lazyPerNestTIME)) {
  # go through master until you find the matching nestID
  for (j in 1:nrow(master)) {
    # if the nest ID matches
    if (lazyPerNestTIME$nestID[i] == master$nestID[j]) {
        lazyPerNestTIME$natal[i] <- master$Wnatal[j]
      }
    }
  }
```

# glmms on number of lazy workers across nestTYPEs
```{r}
# it's not normal - lnorm probs
ggdensity(lazyPerNest$nBees)
qqp(lazyPerNest$nBees, "norm")
lazyPerNest$natal

lazyPerNest$totalBees <- NA
lazyPerNest$totalBees[lazyPerNest$nestTYPE == "QF"] <- 6
lazyPerNest$totalBees[lazyPerNest$nestTYPE == "NF"] <- 5
lazyPerNest$totalBees[lazyPerNest$nestTYPE == "QT"] <- 4
lazyPerNest$totalBees[lazyPerNest$nestTYPE == "NT"] <- 3

# need to add natal colony as random effect
ps <- glm(nBees ~ totalBees, 
          data = lazyPerNest, family = poisson(link = "log"))
mymodel <- ps
tab_model(mymodel)

# plot model residuals
plot(fitted(mymodel), residuals(mymodel), xlab = "Fitted Values", ylab = "Residuals")
abline(h = 0, lty = 2)
lines(smooth.spline(fitted(mymodel), residuals(mymodel)))
```

# glmms on number of lazy workers across timepoints
```{r}
# it's not normal - lnorm probs
ggdensity(lazyPerNestTIME$nBees)
qqp(lazyPerNestTIME$nBees, "norm")
lazyPerNestTIME$natal

lazyPerNestTIME$totalBees <- NA
lazyPerNestTIME$totalBees[lazyPerNestTIME$nestTYPE == "QF"] <- 6
lazyPerNestTIME$totalBees[lazyPerNestTIME$nestTYPE == "NF"] <- 5
lazyPerNestTIME$totalBees[lazyPerNestTIME$nestTYPE == "QT"] <- 4
lazyPerNestTIME$totalBees[lazyPerNestTIME$nestTYPE == "NT"] <- 3

# need to add natal colony as random effect
ps0 <- glm(nBees ~ 1, 
          data = lazyPerNestTIME, family = poisson(link = "log"))
ps1 <- glm(nBees ~ totalBees + timepoint, 
          data = lazyPerNestTIME, family = poisson(link = "log"))
ps2 <- glm(nBees ~ totalBees, 
          data = lazyPerNestTIME, family = poisson(link = "log"))
ps3 <- glm(nBees ~ timepoint, 
          data = lazyPerNestTIME, family = poisson(link = "log"))
model.sel(ps0, ps1, ps2, ps3)

mymodel <- ps2
tab_model(mymodel)
posthoc1 <- glht(mymodel, linfct = mcp(nestTYPE = "Tukey"))
summary(posthoc1)

# plot model residuals
plot(fitted(mymodel), residuals(mymodel), xlab = "Fitted Values", ylab = "Residuals")
abline(h = 0, lty = 2)
lines(smooth.spline(fitted(mymodel), residuals(mymodel)))
```