---
title: "Repeatability Analysis"
output: pdf_document
fig.width: 6
fig.height: 15
---
#Need to run after Shannon Bees 
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# load packages
```{r}
library(tidyverse)
library(dplyr)
library(plyr)
library(ggplot2)
library(cluster) # clustering algorithms
library(factoextra)
library(vegan) 
library(lme4)
library(plotly)
library(ggpubr)
library(car)
library(MASS)
library(MuMIn)
library(lsmeans)
```

# load data
```{r}
read.csv("../Data/filtData/count_time.csv")


#How many observations do we have? (all, early, late)
print(paste("There are", nrow(Allspecrpt), "rows"))
Earlies<-Allspecrpt %>% filter(timepoint=="early") 
Earlies
print(paste("There are", nrow(Earlies), "early rows"))
Laties<-Allspecrpt%>% filter(timepoint=="late") 
print(paste("There are", nrow(Laties), "late rows"))

#Find rows that have only early or only late observations
onlyearly<-anti_join(Earlies, Laties, by="beeID") %>% arrange(beeID)  


earlyexclude<-as.vector(onlyearly$beeID) 
onlylate<-anti_join(Laties,  Earlies, by="beeID") %>% arrange(beeID)
lateexclude<-as.vector(onlylate$beeID)

#Filter our rows that only have one timepoint
Filteredrpt<-Allspecrpt %>% filter(!beeID %in% earlyexclude) %>% filter(!beeID %in% lateexclude)
print(paste("There are", (nrow(Filteredrpt)/2), "individuals for repeatability analyses"))

```



https://cran.r-project.org/web/packages/rptR/vignettes/rptR.html
```{r}
library(rptR)
```




## Repeatability for proportion of behaviors (out of all behaviors except for egglaying)
```{r}

# Make nBehavs for all behaviors but excluding egglaying nFeedFor
rpt_time<-rpt_time %>% mutate(nFeedFor=(feedsbrood+total_for))
# Make proportion columns for each behavior
rpt_prop<-rpt_time %>% mutate(propfb=(feedsbrood/nFeedFor)) %>% 
  mutate(propn=(nectarforaging/nFeedFor)) %>% 
  mutate(propp=pollenforaging/nFeedFor) %>% 
  mutate(propt=total_for/nFeedFor)

#Repeatability proportion brood feeding 
hist(rpt_prop$propfb) # proportion distribution
reppfb<- rpt(propfb ~ timepoint+(1|beeID)+(1|nestID),
            grname = c("beeID", "nestID"), data = rpt_prop, 
            datatype = "Proportion", nboot = 1000, npermut = 0)
summary(reppfb)
print(reppfb)
plot(reppfb, cex.main = 1)

#Repeatability proportion nectar foraging
reppnf<- rpt(propn ~ timepoint+(1|beeID)+(1|nestID),
            grname = c("beeID", "nestID"), data = rpt_prop, 
            datatype = "Proportion", nboot = 1000, npermut = 0)
summary(reppnf)
print(reppnf)
plot(reppnf, cex.main = 1)

#Repeatability proportion pollen foraging 
reppf<- rpt(propp ~ timepoint+(1|beeID)+(1|nestID),
            grname = c("beeID", "nestID"), data = rpt_prop, 
            datatype = "Proportion", nboot = 1000, npermut = 0)
summary(reppf)
print(reppf)
plot(reppf, cex.main = 1)

#Repeatability proportion total foraging
reppf<- rpt(propp ~ timepoint+(1|beeID)+(1|nestID),
            grname = c("beeID", "nestID"), data = rpt_prop, 
            datatype = "Proportion", nboot = 1000, npermut = 0)
summary(reppf)
print(reppf)
plot(reppf, cex.main = 1)




```



























































