---
title: "CleanData"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
  
# Load Packages
```{r}
library(tidyverse)
library(dplyr)
```

# Load Data
```{r}

## create a list of all the files in the BORISfiles directory. these are all the files we want to import
## directory will change depending on user, to find your file path, use command "pwd" 
borisfiles <- list.files("/Users/kaleighfisher/Google Drive File Stream/My Drive/WoodardLab.shared/Projects/2018.Awesome.Summer.Experiments/Raw Data") 


## loop over the files and import all of them. rename column names to remove "." and make shorter
lapply(borisfiles, read.csv, header = TRUE, col.names = c("obsID", "obsDate", "filename", "totalLen", "fps", "beeID", "behav", "mod", "behavType", "start", "stop", "dur", "comStart", "comStop"))

## merge the files into one dataframe (do.call does stuff to all the things)
## this is NOT CORRECT! need to edit to make it work
do.call(rbind(filename))




##
## load a subset of data to test
all_data <- read.csv("/Users/ericasarro/Google\ Drive\ File\ Stream/My\ Drive/MasterProjects/18Su_AwesomeSummer/MockData/AggEvents.csv", header = TRUE, col.names = c("obsID", "obsDate", "filename", "totalLen", "fps", "beeID", "behav", "mod", "behavType", "start", "stop", "dur", "comStart", "comStop" ))
head(all_data)

```

# Clean Data
```{r}

## convert columns to character to enable manipulation with strsplit() and subset(startsWith())
all_data$beeID <- as.character(all_data$beeID)
all_data$obsID <- as.character(all_data$obsID)

## split out obsID into camID, nestID, dateID and hourID (split based on the tab (\t) between elements)
## element 1 is camID
all_data$camID <- sapply(strsplit(all_data$obsID, "\t"), 
                          function(x){
                            x[1]
                            } )
## element 2 is nestID
all_data$nestID <- sapply(strsplit(all_data$obsID, "\t"), 
                          function(x){
                            x[2]
                            } )
## element 3 is dateID
all_data$dateID <- sapply(strsplit(all_data$obsID, "\t"), 
                          function(x){ 
                            x[3]
                            } )
## element 4 is hourID
all_data$hourID <- sapply(strsplit(all_data$obsID, "\t"), 
                          function(x){ 
                            x[4]
                            } )
```

```{r}
## collapse the dataframe to count the number of instances doing each behavior
## this outputs a new dataframe with columns nestID, beeID, nectarforaging, feedsbrood, pollenforaging 
#  (and any other behaviors recorded), with counts for each behavior in as values
## produces error: Values in `dur` are not uniquely identified; output will contain list-cols. 
#  but seems to be working anyway? table doesn't always show up with values (sometimes says <S3: vctrs_list_of>), 
#  but when you pull out a specific value (ie. count_data[3,4]) it comes up with the right number
count_data <- all_data %>%
  pivot_wider(id_cols = c("nestID", "beeID"), names_from = behav, values_from = dur)
count_data

```

```{r}
## make duration of all brood feeding events 1 second duration to enable duration comparisons
time_data <- all_data
for (i in 1:nrow(time_data)) {
  if (time_data$behav[i] == "feedsbrood") {
    time_data$dur[i] <- 1
  }
}
```

```{r}
## collapse dataframe so that columns = nestID, beeID, behav, and stop times for each behavior. 
## values = duration of each behav
dur_data <- time_data %>%
  pivot_wider(id_cols = c("nestID", "beeID", "behav"), names_from = stop, values_from = dur)

## add column for sum of duration for each behav
dur_data$totDur <- rowSums(dur_data[4:ncol(dur_data)], na.rm = TRUE)

## subset dataframe so that all is left is nestID, beeID, behav, and totDur
dur_data <- dur_data %>%
  select(nestID, beeID, behav, totDur)

dur_data
```







