---
title: "dataframeInfo"
author: "ES"
date: "8/21/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

All dataframes produced from the clean data file are filtered with the following minimum steps:

1. removed all data from "bad sample" nests. these include nests where the queen 
   or several workers died, food was not replaced, or for some other reason are 
   unusable
2. removed all data from nests that contain less than a threshold duration of 
   total video (threshold defined in the cleanData file)
3. removed all foraging events <10 seconds long (poop trips)
4. removed all nest observations past the 5 minute mark

Any additional filtering is noted below


general overview of naming:
"_data" files include all data from both timepoints pooled together and do not have any additional filtering
"_time" or "Time" files are identical to their non-time counterpart, but are split out by timepoint
"_nests" files are filtered to include only nests with >=3 brood feeding and >=3 foraging events
"_bees" files are filtered to include only bees with >=3 observations


# camDur
--no additional filtering
camDur contains the duration in seconds of video watched for all nests, split 
out by early, late, nest, and foraging
  
  rows: rows represent individual nests
      one row per nestID
  columns:
      nestID = nestID
      forLen = seconds of total foraging video
      nestLen = seconds of total nest video
      totalLen = seconds of total video
      FNratio = ratio of foraging to nest video
      earlyFor = seconds of early foraging video
      earlyNest = seconds of early nest video
      lateFor = seconds of late foraging video
      lateNest = seconds of late nest video
      earlyLen = seconds of early video
      lateLen = seconds of late video
      
# obs
obs files report the boris observation outputs
## obs_data
--no additional filtering
obs_data contains observation information in the format of boris downloads, with bees with 0 observations added on. it includes all bees in the experiment -- including identified bees with observations, unidentified bees with observations, and bees without observations, including bees that died at some point or were replaced throughout the experiment

  rows: rows represent individual observations of individual bees
      one or more rows per bee (at least 1 row for EVERY bee). bees with 0-1 
      observations have a single row in the df, bees with >1 observations have 
      the same number of rows as observations
  columns:
      obsID = observation ID (boris output, eg., "nest NF12 20180627 20")
      obsDate = date and of camera observation
      totalLen = seconds in that entire video observation (eg., 300)
      beeID = combined nestID and beeID for the bee (eg., NF0182), unidentified
            bees are in the format "NF01unknown"
      behav = behavior observed (eg., feedsbrood)
      start = time relative to the beginning of the video that the behavior
            began
      stop = time relative to the beginning of the video that the behavior ends
      dur = duration of the behavior (feedsbrood duration = 1)
      camID = nest or foraging camera, "non" if unknown
      nestID = nestID
      dateID = date of camera observation in the format YYYYmmdd
      hourID = time of the camera observation (hour only, eg., "3", "17")
      caste = caste of bee, W or Q. all unidentified bees marked W
      nestTYPE = nest type
      natal = natal colony for that bee (unknown bees marked NA)
      beeType = original bee ("orig") or replacement bee ("replac") if added 
            later (unknown bees marked NA)
      addDate = date of addition to the nest, if replacement bee, YYYYmmdd
      diedDate = date of death, if the bee died during the experiment, YYYYmmdd

## obs_time
--filtered to remove bees with 0 recorded behaviors
obs_time is in the same format as obs_data, but only includes bees with recorded observations, including unidentified bees (*bees with 0 observations are not included in this df). for each observation, timepoint information (early or late) is included as a column

  rows: rows represent individual observations of individual bees
      one or more rows per bee, # rows per bee = # observations per bee
  columns: columns are identical to obs_data, with the addition of timepoint
      obsID = observation ID (boris output, eg., "nest NF12 20180627 20")
      obsDate = date and of camera observation
      totalLen = seconds in that entire video observation (eg., 300)
      beeID = combined nestID and beeID for the bee (eg., NF0182), unidentified
            bees are in the format "NF01unknown"
      behav = behavior observed (eg., feedsbrood)
      start = time relative to the beginning of the video that the behavior
            began
      stop = time relative to the beginning of the video that the behavior ends
      dur = duration of the behavior (feedsbrood duration = 1)
      camID = nest or foraging camera, "non" if unknown
      nestID = nestID
      dateID = date of camera observation in the format YYYYmmdd
      hourID = time of the camera observation (hour only, eg., "3", "17")
      caste = caste of bee, W or Q. all unidentified bees marked W
      nestTYPE = nest type
      natal = natal colony for that bee (unknown bees marked NA)
      beeType = original bee ("orig") or replacement bee ("replac") if added 
            later (unknown bees marked NA)
      addDate = date of addition to the nest, if replacement bee, YYYYmmdd
      diedDate = date of death, if the bee died during the experiment, YYYYmmdd
      timepoint = whether the observatiton occured in the first ("early") or
                  second ("late") bout of video watching
                  
## obs_nests
--filtered to remove nests with fewer than 3 recorded brood feeding behaviors and 3 recorded foraging behaviors
obs_nests is in the same format as obs_data, but only includes nests with at least 3 observations each of brood feeding and total foraging. includes unidentified bees and bees with 0 recorded observations

  rows: rows represent individual observations of individual bees
      one or more rows per bee for nests with >threshold observations, including 
      unknown bees and bees with 0 observations
  columns: columns are identical to obs_data
      obsID = observation ID (boris output, eg., "nest NF12 20180627 20")
      obsDate = date and of camera observation
      totalLen = seconds in that entire video observation (eg., 300)
      beeID = combined nestID and beeID for the bee (eg., NF0182), unidentified
            bees are in the format "NF01unknown"
      behav = behavior observed (eg., feedsbrood)
      start = time relative to the beginning of the video that the behavior
            began
      stop = time relative to the beginning of the video that the behavior ends
      dur = duration of the behavior (feedsbrood duration = 1)
      camID = nest or foraging camera, "non" if unknown
      nestID = nestID
      dateID = date of camera observation in the format YYYYmmdd
      hourID = time of the camera observation (hour only, eg., "3", "17")
      caste = caste of bee, W or Q. all unidentified bees marked W
      nestTYPE = nest type
      natal = natal colony for that bee (unknown bees marked NA)
      beeType = original bee ("orig") or replacement bee ("replac") if added 
            later (unknown bees marked NA)
      addDate = date of addition to the nest, if replacement bee, YYYYmmdd
      diedDate = date of death, if the bee died during the experiment, YYYYmmdd
                  
# count
count files summarize the number of observations in the obs files into counts
## count_data
--no additional filtering
count_data summarizes (counts) the number of observations of each behavior per bee and includes all known information about the bees (eg., ovary data,  body size - note that we do not have ovary data for queens), as well as shannon and specialization information. it includes all bees in the experiment -- including identified bees with observations, unidentified bees with observations, and bees without observations, including bees that died at some point or were replaced throughout the experiment. shannon indices are only calculated for bees that are identified and have >=3 observed behaviors

  rows: rows represent individual bees
      one row per bee
  columns: columns summarize all known information about each bee
      nestID = nestID
      nestTYPE = nest type
      beeID = combined nestID and beeID for the bee (eg., NF0182), unidentified
            bees are in the format "NF01unknown"
      caste = caste of bee, W or Q. all unidentified bees marked W
      natal = natal colony for that bee (unknown bees marked NA)
      addDate = date of addition to the nest, if replacement bee, YYYYmmdd
      diedDate = date of death, if the bee died during the experiment, YYYYmmdd
      nectarforaging = number of observed instances of nectar foraging by this
            bee
      feedsbrood = number of observed instances of brood feeding by this bee
      pollenforaging = number of observed instances of pollen foraging by this 
            bee
      egglayinng = number of observed instances of egg laying by this bee
      allforaging = number of observed instances of pollen and nectar foraging
            combined for this bee
      nBehavs = total number of observed behaviors by this bee
      size = average marginal wing cell size for this bee
      ovL1 = length of the longest oocyte on the first ovary
      ovL2 = length of the longest oocyte on the second ovary
      ovR1 = resorption status of the longest oocyte on the first ovary 
            (1 = resorbed, 0 = not resorbed)
      ovR2 = resorption status of the longest oocyte on the second ovary 
            (1 = resorbed, 0 = not resorbed)
      ovS1 = developmental stage of the longest oocyte on the first ovary 
            (resorbed oocytes are entered as stage 4)
      ovS2 = developmental stage of the longest oocyte on the second ovary
            (resorbed oocytes are entered as stage 4)
      shannon = shannon index (only for known bees with >=3 observed behaviors)
      specBehav = specialist behavior category for each bee - specialists have
            a shannon value below a threshold set in the code. "generalists" do 
            not meet this shannon threshold, "lazy" bees have fewer than 3 
            behaviors and therefore do not have a shannon score, unknown bees
            are NA
      specProp = proportion of observed behaviors that were in the specialist 
            category (eg., proportion of all brood feeding behaviors out of all
            behaviors carried out by a given brood-feeding specialist.) NA for
            generalists, lazy bees, and unknown bees
             
## count_time
--filtered to remove bees at a given timepoint that we do not have video data for (eg., if we watched videos for NF02 at late timepoint but not early, there are no rows for bees in NFO2 at the late timepoint)
count_time is made from obs_time, and put into the same format as count_data, split out by timepoint.it summarizes (counts) the number of observations of each behavior per bee at each timepoint and includes all known information about the bees (eg., ovary data and body size as well - note that we do not have ovary data for queens). it includes all bees in the experiment -- including identified bees with observations, unidentified bees with observations, and bees without observations, including bees that died at some point or were replaced throughout the experiment **it does not include rows for bees at timepoints for which we do not have video data

  rows: rows represent individual bees
      one row per bee per timepoint that we watched video (eg., if 
      bee NF0284 has 8 observations at the early timepoint and 0 observations
      at the late timepoint, there will still be 2 rows for this bee - one early
      and one late. however, if we did not watch video at the late timepoint for 
      nest NF02, this bee would only have a single row)
  columns: same as count_data with the addition of timepoint and shanDist and
            exclusion of egglaying
      nestID = nestID
      nestTYPE = nest type
      beeID = combined nestID and beeID for the bee (eg., NF0182), unidentified
            bees are in the format "NF01unknown"
      caste = caste of bee, W or Q. all unidentified bees marked W
      natal = natal colony for that bee (unknown bees marked NA)
      addDate = date of addition to the nest, if replacement bee, YYYYmmdd
      diedDate = date of death, if the bee died during the experiment, YYYYmmdd
      nectarforaging = number of observed instances of nectar foraging by this
            bee
      feedsbrood = number of observed instances of brood feeding by this bee
      pollenforaging = number of observed instances of pollen foraging by this 
            bee
      allforaging = number of observed instances of pollen and nectar foraging
            combined for this bee
      nBehavs = total number of observed behaviors by this bee, excluding egg
            laying
      size = average marginal wing cell size for this bee
      ovL1 = length of the longest oocyte on the first ovary
      ovL2 = length of the longest oocyte on the second ovary
      ovR1 = resorption status of the longest oocyte on the first ovary 
            (1 = resorbed, 0 = not resorbed)
      ovR2 = resorption status of the longest oocyte on the second ovary 
            (1 = resorbed, 0 = not resorbed)
      ovS1 = developmental stage of the longest oocyte on the first ovary 
            (resorbed oocytes are entered as stage 4)
      ovS2 = developmental stage of the longest oocyte on the second ovary
            (resorbed oocytes are entered as stage 4)
      shannon = shannon index (only for known bees with >=3 observed behaviors)
      specBehav = specialist behavior category for each bee - specialists have
            a shannon value below a threshold set in the code. "generalists" do 
            not meet this shannon threshold, "lazy" bees have fewer than 3 
            behaviors and therefore do not have a shannon score, unknown bees
            are NA
      specProp = proportion of observed behaviors that were in the specialist 
            category (eg., proportion of all brood feeding behaviors out of all
            behaviors carried out by a given brood-feeding specialist.) NA for
            generalists, lazy bees, and unknown bees
      timepoint = whether the observatitons, shannon, and specialization info
            apply to the first ("early") or
            second ("late") bout of video watching
      shanDist = change in shannon index from early to late timepoint. this is
            only recorded in the row with late timepoint info for a given bee
            to prevent duplicating data. only calculated for bees with >=3
            behaviors at both timepoints (i.e., they were not lazy at either
            timepoint)

## count_nests
--filtered to remove nests with fewer than 3 recorded brood feeding behaviors and 3 recorded foraging behaviors
count_nests is in the same format as count_data, but only includes nests with at least 3 observations each of brood feeding and total foraging. includes unidentified bees and bees with 0 recorded observations
  rows: rows represent individual bees
      one row per bee, including unknown and lazy bees
  columns: columns are identical to count_data, with the exclusion of shannon, 
      specBehav, and specProp columns
      nestID = nestID
      nestTYPE = nest type
      beeID = combined nestID and beeID for the bee (eg., NF0182), unidentified
            bees are in the format "NF01unknown"
      caste = caste of bee, W or Q. all unidentified bees marked W
      natal = natal colony for that bee (unknown bees marked NA)
      addDate = date of addition to the nest, if replacement bee, YYYYmmdd
      diedDate = date of death, if the bee died during the experiment, YYYYmmdd
      nectarforaging = number of observed instances of nectar foraging by this
            bee
      feedsbrood = number of observed instances of brood feeding by this bee
      pollenforaging = number of observed instances of pollen foraging by this 
            bee
      egglayinng = number of observed instances of egg laying by this bee
      allforaging = number of observed instances of pollen and nectar foraging
            combined for this bee
      nBehavs = total number of observed behaviors by this bee
      size = average marginal wing cell size for this bee
      ovL1 = length of the longest oocyte on the first ovary
      ovL2 = length of the longest oocyte on the second ovary
      ovR1 = resorption status of the longest oocyte on the first ovary 
            (1 = resorbed, 0 = not resorbed)
      ovR2 = resorption status of the longest oocyte on the second ovary 
            (1 = resorbed, 0 = not resorbed)
      ovS1 = developmental stage of the longest oocyte on the first ovary 
            (resorbed oocytes are entered as stage 4)
      ovS2 = developmental stage of the longest oocyte on the second ovary
            (resorbed oocytes are entered as stage 4)
  
## count_nestsTime
--filtered to remove nests with fewer than 3 recorded brood feeding behaviors and 3 recorded foraging behaviors at a given timepoint, excludes egg laying
count_nestsTime is in the same format as count_data, split out by timepoint, but only includes nests with at least 3 observatitons each of brood feeding and total foraging at a given timepoint. includes unidentified bees and bees with 0 recorded behaviors. (eg., if nest NF03 has 2 early observations and 6 late observations, there will be 0 rows for NF03 early in count_nestsTime, and at least one row per bee in the nest at the late timepoint, regardless of whether those bees had recorded observations)
  rows: rows represent individual bees
      one row per bee, including unknown and lazy bees
  columns: columns are identical to count_data, with the addition of timepoint
          and the exclusion of egglaying, shannon, specBehav, specProp, and 
          shanDist
      nestID = nestID
      nestTYPE = nest type
      beeID = combined nestID and beeID for the bee (eg., NF0182), unidentified
            bees are in the format "NF01unknown"
      caste = caste of bee, W or Q. all unidentified bees marked W
      natal = natal colony for that bee (unknown bees marked NA)
      addDate = date of addition to the nest, if replacement bee, YYYYmmdd
      diedDate = date of death, if the bee died during the experiment, YYYYmmdd
      nectarforaging = number of observed instances of nectar foraging by this
            bee
      feedsbrood = number of observed instances of brood feeding by this bee
      pollenforaging = number of observed instances of pollen foraging by this 
            bee
      allforaging = number of observed instances of pollen and nectar foraging
            combined for this bee
      nBehavs = total number of observed behaviors by this bee, excluding egg
            laying
      size = average marginal wing cell size for this bee
      ovL1 = length of the longest oocyte on the first ovary
      ovL2 = length of the longest oocyte on the second ovary
      ovR1 = resorption status of the longest oocyte on the first ovary 
            (1 = resorbed, 0 = not resorbed)
      ovR2 = resorption status of the longest oocyte on the second ovary 
            (1 = resorbed, 0 = not resorbed)
      ovS1 = developmental stage of the longest oocyte on the first ovary 
            (resorbed oocytes are entered as stage 4)
      ovS2 = developmental stage of the longest oocyte on the second ovary
            (resorbed oocytes are entered as stage 4)
      shannon = shannon index (only for known bees with >=3 observed behaviors)
      specBehav = specialist behavior category for each bee - specialists have
            a shannon value below a threshold set in the code. "generalists" do 
            not meet this shannon threshold, "lazy" bees have fewer than 3 
            behaviors and therefore do not have a shannon score, unknown bees
            are NA
      specProp = proportion of observed behaviors that were in the specialist 
            category (eg., proportion of all brood feeding behaviors out of all
            behaviors carried out by a given brood-feeding specialist.) NA for
            generalists, lazy bees, and unknown bees
      timepoint = whether the observation info applies to the first ("early") or
            second ("late") bout of video watching

# prop
prop files summarize the proportion of behaviors per bee from the count files
## prop_bees
--filtered to remove unknown bees and bees with <3 recorded behaviors
prop_bees is made from count_data - unknown and lazy bees are removed, and the counts of each behavior the bee carried out are transformed into the proportion of the total number of behaviors carried out by that given bee

  rows: rows represent individual bees
      one row per known bee with >= recorded behaviors
  columns: columns are identical to count_data, except the behavioral counts
            have been transformed into proportions
      nestID = nestID
      nestTYPE = nest type
      beeID = combined nestID and beeID for the bee (eg., NF0182), unidentified
            bees are in the format "NF01unknown"
      caste = caste of bee, W or Q. all unidentified bees marked W
      natal = natal colony for that bee (unknown bees marked NA)
      addDate = date of addition to the nest, if replacement bee, YYYYmmdd
      diedDate = date of death, if the bee died during the experiment, YYYYmmdd
      nectarforaging = proportion of all behaviors carried out by this bee that 
            are nectar foraging 
      feedsbrood = proportion of all behaviors carried out by this bee that 
            are brood feeding
      pollenforaging = proprtion of all behaviors carried out by this bee that 
            are pollen foraging 
      egglayinng = proportion of all behaviors carried out by this bee that 
            are egg laying
      allforaging = proportion of all behaviors carried out by this bee that 
            are foraging 
      nBehavs = total number of observed behaviors by this bee
      size = average marginal wing cell size for this bee
      ovL1 = length of the longest oocyte on the first ovary
      ovL2 = length of the longest oocyte on the second ovary
      ovR1 = resorption status of the longest oocyte on the first ovary 
            (1 = resorbed, 0 = not resorbed)
      ovR2 = resorption status of the longest oocyte on the second ovary 
            (1 = resorbed, 0 = not resorbed)
      ovS1 = developmental stage of the longest oocyte on the first ovary 
            (resorbed oocytes are entered as stage 4)
      ovS2 = developmental stage of the longest oocyte on the second ovary
            (resorbed oocytes are entered as stage 4)
      shannon = shannon index (only for known bees with >=3 observed behaviors)
      specBehav = specialist behavior category for each bee - specialists have
            a shannon value below a threshold set in the code. "generalists" do 
            not meet this shannon threshold, "lazy" bees have fewer than 3 
            behaviors and therefore do not have a shannon score, unknown bees
            are NA
      specProp = proportion of observed behaviors that were in the specialist 
            category (eg., proportion of all brood feeding behaviors out of all
            behaviors carried out by a given brood-feeding specialist.) NA for
            generalists, lazy bees, and unknown bees
  
## prop_beesTime
--filtered to remove unknown bees and bees with <3 recorded behaviors at a given timepoint
prop_beesTime is made from count_time - unknown and lazy bees at a given timepoint are removed, and the counts of each behavior the bee carried out at a given timepoint are transformed into the proportion of the total number of behaviors carried out by that bee at that timepoint

  rows: rows represent individual bees at a given timepoint
      0-2 rows per bee: 1 row per known bee with >= 3 recorded behaviors per 
      timepoint
  columns: columns are identical to those of prop_bees, with the addition of 
            timepoint
       nestID = nestID
      nestTYPE = nest type
      beeID = combined nestID and beeID for the bee (eg., NF0182), unidentified
            bees are in the format "NF01unknown"
      caste = caste of bee, W or Q. all unidentified bees marked W
      natal = natal colony for that bee (unknown bees marked NA)
      addDate = date of addition to the nest, if replacement bee, YYYYmmdd
      diedDate = date of death, if the bee died during the experiment, YYYYmmdd
      nectarforaging = proportion of all behaviors carried out by this bee that 
            are nectar foraging 
      feedsbrood = proportion of all behaviors carried out by this bee that 
            are brood feeding
      pollenforaging = proportion of all behaviors carried out by this bee that 
            are pollen foraging 
      egglayinng = proportion of all behaviors carried out by this bee that 
            are egg laying
      allforaging = proportion of all behaviors carried out by this bee that 
            are foraging 
      nBehavs = total number of observed behaviors by this bee
      size = average marginal wing cell size for this bee
      ovL1 = length of the longest oocyte on the first ovary
      ovL2 = length of the longest oocyte on the second ovary
      ovR1 = resorption status of the longest oocyte on the first ovary 
            (1 = resorbed, 0 = not resorbed)
      ovR2 = resorption status of the longest oocyte on the second ovary 
            (1 = resorbed, 0 = not resorbed)
      ovS1 = developmental stage of the longest oocyte on the first ovary 
            (resorbed oocytes are entered as stage 4)
      ovS2 = developmental stage of the longest oocyte on the second ovary
            (resorbed oocytes are entered as stage 4)
      shannon = shannon index (only for known bees with >=3 observed behaviors)
      specBehav = specialist behavior category for each bee - specialists have
            a shannon value below a threshold set in the code. "generalists" do 
            not meet this shannon threshold, "lazy" bees have fewer than 3 
            behaviors and therefore do not have a shannon score, unknown bees
            are NA
      specProp = proportion of observed behaviors that were in the specialist 
            category (eg., proportion of all brood feeding behaviors out of all
            behaviors carried out by a given brood-feeding specialist.) NA for
            generalists, lazy bees, and unknown bees
        timepoint = whether the observed proportions apply to the first ("early")
            or second ("late") timepoint
  
  
# task
task files summarize the specialization of tasks 
##taskShan
--filtered to remove nests with fewer than 3 recorded brood feeding behaviors and 3 recorded foraging behaviors
taskShan summarizes the shannon indices of each task within each nest 
  rows: rows represent individual behaviors with individual nests
      4 rows per nest, one for each behavior 
  columns: 
      nestID = nestID
      nestTYPE = nest type
      behav = behavioral category (ie, egglaying, nectarforaging,
            pollenforaging, or feedsbrood)
      nBehav = number of recorded instances of that given behavior in that nest
      shannon = shannon index for that behavior within that nest (unknown bees
            are included as a single individual in this analysis)
      
## taskShanTime
--filtered to remove nests with fewer than 3 recorded brood feeding behaviors and 3 recorded foraging behaviors at a given timepoint, excludes egg laying
taskShanTime summarizes the shannon indices of each task within each nest at each timepoint
  rows: rows represent individual behaviors within individual nests at a given timepoint
      3 rows per nest per timepoint that meets threshold observations
  columns: columns are identical to taskShan, with the addition of timepoint
      nestID = nestID
      nestTYPE = nest type
      behav = behavioral category (ie, egglaying, nectarforaging,
            pollenforaging, or feedsbrood)
      nBehav = number of recorded instances of that given behavior in that nest
      shannon = shannon index for that behavior within that nest (unknown bees
            are included as a single individual in this analysis)
      timepoint = whether the shannon index for a given nest/behavior combo
            refers to the early or late timepoint

# specialists
specialist files summarize the number of behavioral specialists per nest
##nSpecialists
--no additional filtering
nSpecialists summarizes the specBehav column of the count_data df to summarize the number of specialists on each behavior (egglaying, brood feeding, pollen foraging, nectar foraging, generalist, lazy) in each nest
  rows: rows represent nest/behavior combinations
      one row per behavior per nest
  columns: 
      nestID = nest ID
      nestTYPE = nest type
      specBehav = behavioral category (ie, egglaying, feedsbrood, 
            pollenforaging, nectarforaging, generalist, lazy)
      nBeesPerNest = number of bees that fall into that behavioral category in
            that nest
            
## nSpecialistsTime
--no additional filtering
nSpecialists summarizes the specBehav column of the count_time df to summarize the number of specialists of each behavior at each timepoint for each nest
  rows: rows represent nest/behavior combinations at each timepoint
      two rows per behavior per nest (one early, one late), assuming we have
            video data for both timepoints
  columns: columns are identical to nSpecialists with the addition of timepoint
      nestID = nest ID
      nestTYPE = nest type
      specBehav = behavioral category (ie, egglaying, feedsbrood, 
            pollenforaging, nectarforaging, generalist, lazy)
      nBeesPerNest = number of bees that fall into that behavioral category in
            that nest
      timepoint = whether the summary nBeesPerNest relates to the early or late
            time point